apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: fontainerafamant/kube-cours-flask-mysql_app:latest  # Replace with your actual Flask app image
          imagePullPolicy: Never
          # image: nginx
          env:
            - name: DB_URL
              value: "mysql-service.default"  # This should match the service name of MySQL
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000   # Port on the pods
  type: LoadBalancer
